### ISSUE TITLE
Choix de l'algo à utiliser

### ISSUE THREAD

**Issue by rdecamps** [yoannfleurydev/dames#6]
J'ai lu les diapos de la prof et [le cours](https://www.dropbox.com/s/h37gi2kqbnxs074/ia.pdf?dl=0) donné partagé par Francis ;

Je vous fait un résumé du tableau qui compare les 3 algos pour qu'on en choisisse un

## Nombre de noeuds développés pour le jeu Othello
| Profondeur | Minimax | a-B | SSS* |
|:----------------|-----------:|------:|-------:|
| 1 | 3 | 3 | 3 |
| 2 | 14 | 13 | 11 |
| 3 | 61 | 37 | 65 |
| 4 | 349 | 150 | 95 |
| 5 | 2050 | 418 | 292 |
| 6 | 13773 | 1830 | 1617 |

## Temps de calcul pour le jeu Othello
| Profondeur | Minimax | a-B | SSS* |
|:----------------|-----------:|------:|-------:|
| 1 | 0.37 | 0.36 | 0.36 |
| 2 | 1.38 | 1.40 | 1.19 |
| 3 | 6.00 | 3.90 | 3.70 |
| 4 | 32.50 | 14.77 | 10.00 |
| 5 | 185.70 | 41.40 | 19.20 |
| 6 | 1213.50 | 172.90 | 117.30 |

## Avantages / Inconvénients des algos
| Algorithme | Avantages | Inconvénients |
|----------------|----------------|--------------------|
| Minimax | Simple à mettre en place<br>(seulement un parcours en profondeur de la structure) | Parcours intégral de l'arbre |
| a-B | Plus performant que Minimax<br> Elimine certaine branches | Possibilité de parcourir l'ensemble de l'arbre |
| Negamax | Similaire à Minimax, mais tous les noeuds sont des noeuds max | --- |
| SSS* | Produit les meilleurs résultats | Peu être très couteux en mémoire<br>(construction de chaque état du jeu à la profondeur *p*)<br>Plus complexe à implémenter |

Je partirais bien sur du SSS* (la mémoire utilisée jusqu'à un niveau de profondeur 3 doit pas être si élevé que ça)

Dites moi ce que vous en pensez :) savoir si on part sur du ultra performant ou un truc simple à implémenter :)

**Comment by yoannfleurydev** [comment]
Je partirai bien sur SSS* également. Il nous faut un temps de calcul correct. On pourra même tenter une profondeur plus grande. A voir.

**Comment by VincentBerniere** [comment]
Personnellement j'ai toujours pas compris SSS*, a-B à l'air plus simple à implémenter et le temps de calcul est assez proche de SSS* quand même.

**Comment by yoannfleurydev** [comment]
Le choix se porte finalement sur αβ

@valentincro
